name: CI
on:
  pull_request:
    branches: [ "main" ]   # Esto hace que el workflow se ejecute cuando haya un pull request hacia la rama main.
  workflow_call:  # Esto permite que otro workflow pueda invocar este workflow directamente.
jobs:
  html-validator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: HTML validator
      run: docker run --rm -v ${{ github.workspace }}/src:/src ghcr.io/validator/validator:latest vnu /src/index.html
